spring:
  application:
    name: tracker

bank-account:
  messaging:
    queues:
      transaction: bank-account.transactions
      audit: bank-account.audit
  tracker:
    performance:
      enabled: false
    submission:
      submission-size: 1000
      initial-buffer-count: 2
      max-buffer-count: 10
      max-batch-total: 1000000
